/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ordersystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ak
 */
public class Customers extends javax.swing.JFrame {

    String name_sch,sql;
    public Customers() {
        initComponents();
        setLocationRelativeTo(this);
        
        btnState(1, 0, 0, 0);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCust_no = new javax.swing.JTextField();
        txtCust_name = new javax.swing.JTextField();
        txtCust_add = new javax.swing.JTextField();
        txtCust_tel = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnCust_del = new javax.swing.JButton();
        btnCust_edt = new javax.swing.JButton();
        btnCust_sav = new javax.swing.JButton();
        btnCust_new = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCust_show = new javax.swing.JTable();
        txtCust_sch = new javax.swing.JTextField();

        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new java.awt.GridLayout(0, 1, 0, 13));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("رقم الزبون");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("الاسم ");
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("العنوان");
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("رقم التلفون");
        jPanel1.add(jLabel4);

        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 0, 13));

        txtCust_no.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtCust_no.setForeground(new java.awt.Color(51, 51, 51));
        txtCust_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCust_no.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));
        txtCust_no.setFocusable(false);
        txtCust_no.setName("txtCust_no"); // NOI18N
        jPanel3.add(txtCust_no);

        txtCust_name.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtCust_name.setForeground(new java.awt.Color(51, 51, 51));
        txtCust_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCust_name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));
        txtCust_name.setName("txtCust_name"); // NOI18N
        jPanel3.add(txtCust_name);

        txtCust_add.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtCust_add.setForeground(new java.awt.Color(51, 51, 51));
        txtCust_add.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCust_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));
        txtCust_add.setName("txtCust_add"); // NOI18N
        jPanel3.add(txtCust_add);

        txtCust_tel.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        txtCust_tel.setForeground(new java.awt.Color(51, 51, 51));
        txtCust_tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCust_tel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 1, true));
        txtCust_tel.setName("txtCust_tel"); // NOI18N
        jPanel3.add(txtCust_tel);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 13, 0));

        btnCust_del.setBackground(new java.awt.Color(0, 51, 51));
        btnCust_del.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        btnCust_del.setForeground(new java.awt.Color(255, 255, 255));
        btnCust_del.setText("حذف");
        btnCust_del.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCust_del.setName("btnCust_del"); // NOI18N
        btnCust_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust_delActionPerformed(evt);
            }
        });
        jPanel5.add(btnCust_del);

        btnCust_edt.setBackground(new java.awt.Color(0, 51, 51));
        btnCust_edt.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        btnCust_edt.setForeground(new java.awt.Color(255, 255, 255));
        btnCust_edt.setText("تعديل");
        btnCust_edt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCust_edt.setName("btnCust_edt"); // NOI18N
        btnCust_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust_edtActionPerformed(evt);
            }
        });
        jPanel5.add(btnCust_edt);

        btnCust_sav.setBackground(new java.awt.Color(0, 51, 51));
        btnCust_sav.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        btnCust_sav.setForeground(new java.awt.Color(255, 255, 255));
        btnCust_sav.setText("حفظ");
        btnCust_sav.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCust_sav.setName("btnCust_sav"); // NOI18N
        btnCust_sav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust_savActionPerformed(evt);
            }
        });
        jPanel5.add(btnCust_sav);

        btnCust_new.setBackground(new java.awt.Color(0, 51, 51));
        btnCust_new.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        btnCust_new.setForeground(new java.awt.Color(255, 255, 255));
        btnCust_new.setText("جديد");
        btnCust_new.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCust_new.setName("btnCust_new"); // NOI18N
        btnCust_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCust_newActionPerformed(evt);
            }
        });
        jPanel5.add(btnCust_new);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tblCust_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "التلفون", "العنوان", "الاسم", "رقم الزبون"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCust_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCust_showMouseClicked(evt);
            }
        });
        tblCust_show.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblCust_showPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tblCust_show);

        txtCust_sch.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        txtCust_sch.setForeground(new java.awt.Color(102, 102, 102));
        txtCust_sch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCust_sch.setText("بحث");
        txtCust_sch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 1, true));
        txtCust_sch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtCust_schCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addComponent(txtCust_sch))
                .addGap(29, 29, 29)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCust_sch, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCust_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust_newActionPerformed
        
        txtState();
        
        btnState(0, 1, 0, 0);
        
    }//GEN-LAST:event_btnCust_newActionPerformed

    private void btnCust_savActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust_savActionPerformed
        if (!(txtCust_name.getText().isBlank())){
            String cust_name,cust_add,cust_tel,sql;
            
            cust_name=txtCust_name.getText();
            cust_add=txtCust_add.getText();
            cust_tel=txtCust_tel.getText();
           
            sql="insert into customers(cust_name,cust_add,cust_tel) "
                    + "values('"+cust_name+"','"+cust_add+"','"+cust_tel+"');";
            
            if (DB.Calldb.saveData(sql)){
                JOptionPane.showMessageDialog(null, "تم الحفظ بنجاح.");
                
                txtState();
                
                btnState(0, 1, 0, 0);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "لم تتم العملية.");
               
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "يرجى ملئ الحقول المطلوبة.");
        }
        refreshTable(tblCust_show);
    }//GEN-LAST:event_btnCust_savActionPerformed

    private void btnCust_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust_delActionPerformed
         if (!txtCust_no.getText().isBlank()){
        int cust_no;
        String sql;
        cust_no=Integer.valueOf(txtCust_no.getText());
        sql="delete from customers where cust_no="+cust_no+";";
        
         if (DB.Calldb.deleteData(sql)){
            JOptionPane.showMessageDialog(null, "تم الحذف بنجاح.");
            
            txtState();
            
            btnState(0,1,0,0);
        }
        else{
            JOptionPane.showMessageDialog(null, "لم تتم العملية.");
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "يرجى ملئ حقل الرقم.");
        }
         refreshTable(tblCust_show);
    }//GEN-LAST:event_btnCust_delActionPerformed

    private void btnCust_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCust_edtActionPerformed
        
        if (!(txtCust_name.getText().isBlank())){
            String cust_name,cust_add,cust_tel,sql;
            int cust_no;
            
            cust_no=Integer.valueOf(txtCust_no.getText());
            cust_name=txtCust_name.getText();
            cust_add=txtCust_add.getText();
            cust_tel=txtCust_tel.getText();
            sql="update customers set cust_name='"+cust_name+"',"
                    + "cust_add='"+cust_add+"',"
                    + "cust_tel='"+cust_tel+"'where cust_no='"+cust_no+"';";
            
            
            if (DB.Calldb.updateData(sql)){
                JOptionPane.showMessageDialog(null, "تم التعديل بنجاح.");
                
                txtState();
                btnState(0, 1, 0, 0);
            }
            else{
                JOptionPane.showMessageDialog(null, "لم تتم العملية.");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "يرجى ملئ كل الحقول.");
            
        }
        refreshTable(tblCust_show);
        
    }//GEN-LAST:event_btnCust_edtActionPerformed

    private void tblCust_showPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblCust_showPropertyChange
        refreshTable(tblCust_show);
    }//GEN-LAST:event_tblCust_showPropertyChange

    private void tblCust_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCust_showMouseClicked
        
         if (tblCust_show.getSelectedRow()>-1){
             
            int r=tblCust_show.getSelectedRow();
            
            txtCust_no.setText(String.valueOf(tblCust_show.getValueAt(r, 3)));
            txtCust_name.setText(String.valueOf(tblCust_show.getValueAt(r, 2)));
            txtCust_add.setText(String.valueOf(tblCust_show.getValueAt(r, 1)));
            txtCust_tel.setText(String.valueOf(tblCust_show.getValueAt(r, 0)));
             
            btnState(1, 0, 1, 1);
         }
    }//GEN-LAST:event_tblCust_showMouseClicked

    private void txtCust_schCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtCust_schCaretUpdate
       name_sch=txtCust_sch.getText();
       sql="select cust_no,cust_name,cust_add,cust_tel from customers where cust_name like'%"+name_sch+"%';";
       DB.Calldb.showData(sql, tblCust_show);
    }//GEN-LAST:event_txtCust_schCaretUpdate

    
      public static void refreshTable(JTable table){
        String sql;
        sql="select cust_no,cust_name,cust_add,cust_tel from customers;";
        
        DB.Calldb.showData(sql, table);
    }
    
    public void btnState(Integer n,int s,int e,int d) {
            btnCust_new.setEnabled(MainForm.numberToBool(n));
            btnCust_sav.setEnabled(MainForm.numberToBool(s));
            btnCust_edt.setEnabled(MainForm.numberToBool(e));
            btnCust_del.setEnabled(MainForm.numberToBool(d));
          
    }
    
    private void txtState(){
        txtCust_no.setText("");
        txtCust_name.setText("");
        txtCust_add.setText("");
        txtCust_tel.setText("");
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customers().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCust_del;
    private javax.swing.JButton btnCust_edt;
    private javax.swing.JButton btnCust_new;
    private javax.swing.JButton btnCust_sav;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCust_show;
    private javax.swing.JTextField txtCust_add;
    private javax.swing.JTextField txtCust_name;
    private javax.swing.JTextField txtCust_no;
    private javax.swing.JTextField txtCust_sch;
    private javax.swing.JTextField txtCust_tel;
    // End of variables declaration//GEN-END:variables
}
